site_name: Dibyendu SIKDAR
site_description: Offensive & Defesive Operations covering Web, Cloud, Infra, IOT and many more..
theme:
  name: material
  palette:
    scheme: slate
    primary: light green
  font:
    code: Roboto Serif
plugins:
  - search
  - blog:
      blog_dir: .
      post_excerpt: optional  # Enable excerptse
      
  - tags
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
