site_name: Dibyendu SIKDAR
site_description: Offensive & Defesive Operations covering Web, Cloud, Infra, CTFs and many more..
theme:
  name: material
  palette:
    scheme: slate
    primary: lime
  font:
    code: Roboto Serif
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - blog:
      blog_dir: .
      post_excerpt: optional  # Enable excerptse
      
  - tags
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  
nav:
  - Home: index.md
  - Blog: blog/index.md
  - Docs:
      - Getting Started: docs/getting-started.md
      - Tools: docs/tools.md
  - About: about.md
  - GitHub: https://github.com/your-org/your-repo